set -l CMDS init new-branch merge checkout update-prs update delete open-config
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a init -d 'Initialise a new PR train'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a new-branch -d 'Create a new tail branch'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a merge -d 'Merge each branch from origin/green to the tail'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a checkout -d 'Checkout the head/tail/nth branch'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a update-prs -d 'Create & update PRs for all branches'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a update -d 'Remove merged branches from the PR train config'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a delete -d 'Delete the current PR train'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a open-config -d 'Open the PR train config file'
complete -f -c pr-train -n "not __fish_seen_subcommand_from $CMDS" -a --status -d 'Show the current PR train'